version: '3.4'
services:
  app:
    image: 127.0.0.1:5000/distributed_groceries
    build: .
    environment:
      PORT: 4000
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - distributed_groceries

networks:
  distributed_groceries:
